SELECTABLE_WEIGHTED_TOWERS = [
    {"Anarchist": 7},
    {"Aviator": 12},
    {"Barracks": 7},
    {"Commander": 25},
    {"Commando": 18},
    {"Cryo-Gunner": 5},
    {"DJ": 25},
    {"Enforcer": 3},
    {"FlameThrower": 7},
    {"Fragger": 7},
    {"Marksman": 18},
    {"Mercenary": 18},
    {"Mortar": 25},
    {"Patrol": 12},
    {"Phaser": 7},
    {"Plasma Trooper": 12},
    {"Railgunner": 12},
    {"Scout": 3},
    {"Shotgunner": 5},
    {"Sniper": 5},
    {"Soldier": 18},
    {"Tuber": 7},
    {"Zed": 12}
]

VARIABLE_WEIGHTED_TOWERS = [
    {"Golden Scout": 12},
    {"Golden Commando": 18},
    {"Scarecrow": 3},
    {"Elf": 7},
    {"Hallowboomer": 12},
    {"Sleeter": 7},
    {"Graveyard": 12},
    {"Harpoon Hunter": 12},
    {"Tweeter": 5},
    {"Snowballer": 5},
    {"Patrioteer": 3},
    {"Red Scout": 3},
    {"Sniper but red": 5},
    {"Huntsman": 18},
    {"Resting Soldier": 1},
    {"Monkey": 1},
    {"Poopi": 1}
]
